SRCS=BombEffect.cpp    enemy_tank.cpp   MoveObjectState.cpp  tank.cpp
bullet.cpp	   game.cpp	     my_bullet.cpp	   TankState.cpp
BulletState.cpp   GameObject.cpp   mytank.cpp	   utils.cpp
C2DMatrix.cpp	   main.cpp	     MyTankState.cpp	   Vector2d.cpp
enemy_bullet.cpp  move_object.cpp  ResourceManager.cpp

OBJS=BombEffect.o    enemy_tank.o   MoveObjectState.o  tank.o
bullet.o	   game.o	     my_bullet.o	   TankState.o
BulletState.o   GameObject.o   mytank.o	   utils.o
C2DMatrix.o	   main.o	     MyTankState.o	   Vector2d.o
enemy_bullet.o  move_object.o  ResourceManager.o


